# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.getMeterReadings_pb2 as getMeterReadings__pb2


class GetMeterReadingsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetData = channel.unary_unary(
                '/getmeterreadings.GetMeterReadings/GetData',
                request_serializer=getMeterReadings__pb2.GetMeterReadingsRequest.SerializeToString,
                response_deserializer=getMeterReadings__pb2.GetMeterReadingsResponse.FromString,
                )


class GetMeterReadingsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetMeterReadingsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=getMeterReadings__pb2.GetMeterReadingsRequest.FromString,
                    response_serializer=getMeterReadings__pb2.GetMeterReadingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'getmeterreadings.GetMeterReadings', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetMeterReadings(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/getmeterreadings.GetMeterReadings/GetData',
            getMeterReadings__pb2.GetMeterReadingsRequest.SerializeToString,
            getMeterReadings__pb2.GetMeterReadingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
