# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getMeterReadings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16getMeterReadings.proto\x12\x10getmeterreadings\x1a\x1fgoogle/protobuf/timestamp.proto\"\x19\n\x17GetMeterReadingsRequest\"H\n\x07reading\x12\x13\n\x0bmeter_usage\x18\x01 \x01(\x01\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"G\n\x18GetMeterReadingsResponse\x12+\n\x08readings\x18\x01 \x03(\x0b\x32\x19.getmeterreadings.reading2v\n\x10GetMeterReadings\x12\x62\n\x07GetData\x12).getmeterreadings.GetMeterReadingsRequest\x1a*.getmeterreadings.GetMeterReadingsResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'getMeterReadings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETMETERREADINGSREQUEST._serialized_start=77
  _GETMETERREADINGSREQUEST._serialized_end=102
  _READING._serialized_start=104
  _READING._serialized_end=176
  _GETMETERREADINGSRESPONSE._serialized_start=178
  _GETMETERREADINGSRESPONSE._serialized_end=249
  _GETMETERREADINGS._serialized_start=251
  _GETMETERREADINGS._serialized_end=369
# @@protoc_insertion_point(module_scope)
